framework:
    rate_limiter:
        email_resend:
            policy: 'fixed_window'
            limit: 3
            interval: '15 minutes'
        
        forgot_password:
            policy: 'fixed_window'
            limit: 10
            interval: '15 minutes'