security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        api_public:
            pattern: ^/api/public
            security: false

        api:
            pattern: ^/api
            stateless: false
            provider: app_user_provider
            context: main
            user_checker: App\Security\UserChecker
            custom_authenticators:
                - App\Security\JwtAuthenticator
            entry_point: App\Security\JwtAuthenticator

        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            entry_point: form_login
            form_login:
                login_path: app_login_page
                check_path: app_login_page
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                csrf_token_id: authenticate
                default_target_path: /notes
            logout:
                path: app_logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 1209600
                path: /

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/public, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/verify/email, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/notes, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 10 # Slightly higher cost for better compatibility
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
