version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: snipnote_app
    restart: unless-stopped
    working_dir: /srv/app
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      APP_SECRET: "change-me"
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/notes_db?serverVersion=15&charset=utf8"
    volumes:
      - .:/srv/app:cached
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: snipnote_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: snipnote_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
